env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[f3f0e431932da8034e9afa4239285f6597d4d4af20431a3390a9ae258dbd443b78ed7bf75c7c53d3d1a0b1bb19f8eaff]"
  TG_TOKEN: "ENCRYPTED[1da8b40df942b1f5739b81a2c4a20da6d20986ece8b6243c5253bafae01d8be013b5487ab4dd81924a1123f436785eb3]"
  TG_CHAT_ID: "ENCRYPTED[0bbc3f803ce6c8a44293f3c5e560891fd5f29c9763329f29d68202ddff8ef322144062cfc526ec206c4001b685f77efd]"
  SF_USER: "ENCRYPTED[f995d02505f24c442a558a8e4ef95c66e8030ba5a1deff4eae38e99ebfce86b85dc7d9c1f59c82fa3ff30ffda36b785d]"
  SF_PASS: "ENCRYPTED[d99ac59c6fbe786da53172e509becd0d7d88b0d6251b1d58993b9ea34367cedf4aaba614cd4efc94e3745a31b87d104d]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "BananaDroid Build"
  stateful: true
  timeout_in: 120m
  container:
    image: d34dpul32/ubuntu:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_script:
     - ./script/load_ccache.sh

  Repo-pribadi_script:
     - git config --global user.name "PunisherxD"
     - git config --global user.email "metamovies69@gmail.com"

  Sinkronasi-rom_script:
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Start sync Source"
     - ./script/sync.sh
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sync Completed!"
     
  Membangun-rom_script:
     - ./script/building.sh
     
  Ccache-informasi_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Mengunggah-build_script:
     - ./script/ziping.sh
